name: BlockHat
main: me.nmc94.BlockHat.BlockHat
version: 1.12
authors: [nmc94, Olof, cnaude]
softdepend: [Vault]
commands:
  blockhat:
    description: Puts blocks on players heads
    aliases: [hat]
    usage: |
           /<command> [[group <group>|<player>] <block>|ver|help]
           Example: /<command> ver- Prints the version.
           Example: /<command> help- Prints the help.
           Example: /<command> - Puts the held block on your head.
           Example: /<command> 1 - Puts the block with id 1 (stone) on your head.
           Example: /<command> nmc94 sand - Puts sand on nmc94's head.
           Example: /<command> group admin TnT - Puts tnt on all the players in the admin group heads.
  unhat:
    description: Removes player's hat.
permissions:
  blockhat.hat:
    default: op
    description: Allows you to use /hat
  blockhat.hat.items:
    default: op
    description: Allows you to use /hat [item id]
  blockhat.hat.give.players.items:
    default: op
    description: Allows you to use /hat [player name] [item id]
  blockhat.hat.give.groups.items:
    default: op
    description: Allows you to use /hat group [group name] [item id]
  blockhat.return:
    default: op
    description: Returns a player's hat to their inventory when replaced or removed
  blockhat.unhat:
    default: op
    description: Allows you to use /unhat